### ISSUE TITLE
brew install sunnyyoung/repo/wechattweak-cli报了这个错误，这是什么原因

### ISSUE THREAD

**Issue by ezjason** [sunnyyoung/WeChatTweak#676]
/usr/local/Homebrew/Library/Homebrew/version.rb:368:in `initialize': Version value must be a string; got a NilClass () (TypeError)
	from /usr/local/Homebrew/Library/Homebrew/os/mac/version.rb:26:in `initialize'
	from /usr/local/Homebrew/Library/Homebrew/os/mac.rb:24:in `new'
	from /usr/local/Homebrew/Library/Homebrew/os/mac.rb:24:in `version'
	from /usr/local/Homebrew/Library/Homebrew/os/mac.rb:58:in `prerelease?'
	from /usr/local/Homebrew/Library/Homebrew/os.rb:21:in `<module:OS>'
	from /usr/local/Homebrew/Library/Homebrew/os.rb:3:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/Homebrew/Library/Homebrew/global.rb:37:in `<top (required)>'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:23:in `require_relative'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:23:in `<main>'

**Comment by fjiabinc** [comment]
我同样是报错:微信版本3.8.2
------ Download ------
Install failed: Download failed with error: sessionTaskFailed(error: Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={_kCFStreamErrorCodeKey=60, NSUnderlyingError=0x600000294120 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)" UserInfo={_NSURLErrorNWPathKey=satisfied (Path is satisfied), interface: en0[802.11], ipv4, ipv6, dns, _kCFStreamErrorCodeKey=60, _kCFStreamErrorDomainKey=1}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDownloadTask <94B37C07-C3CB-487F-87C4-1864F58E5075>.<1>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDownloadTask <94B37C07-C3CB-487F-87C4-1864F58E5075>.<1>"
), NSLocalizedDescription=The request timed out., NSErrorFailingURLStringKey=https://github.com/Sunnyyoung/WeChatTweak-macOS/releases/latest/download/WeChatTweak.framework.zip, NSErrorFailingURLKey=https://github.com/Sunnyyoung/WeChatTweak-macOS/releases/latest/download/WeChatTweak.framework.zip, _kCFStreamErrorDomainKey=1})

**Comment by sunnyyoung** [comment]
brew 环境问题

**Comment by sunnyyoung** [comment]
Closing due to inactivity.
